### ISSUE TITLE
Drafting up gateway setup on Raspberry Pi documentation

### ISSUE THREAD

**Issue by magicpia** [magic-network/magic-agent#2]
We're working on several user guides for installing Magic Agent on different setups. In the meantime, here are some notes for the Raspberry Pi to get folks started (cc: @drmartens). Let us know if you encounter issues in this thread. We'll iterate through it and publish a document once its stable.

## Using a Raspberry Pi as a Gateway
For this tutorial, we’ve dedicated a Raspberry Pi 3 Model B to serve as a gateway. 

If you already have a Pi setup that is connected to an existing internet connection, simply follow the instructions below to install Magic Agent on the Pi.

If you are starting from scratch and need to setup your Pi follow the “Start from scratch” instructions [forthcoming].

## Raspberry Pi Pre-requisites
- Running Raspbian (Lite is sufficient)
- Connected to the internet

Note: The Pi should be connected to the internet on the same network as you are planning to install Magic and needs to maintain internet connectivity in order to serve as a gateway for Magic Clients to connect through.

## Install Magic Pre-requisites
**Install git**
```Sudo apt install git```

**Install pip**
```Sudo apt install python-pip```

**Install Docker**
```curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh```

**Install Docker Compose**
```sudo pip install docker-compose```

## Install Magic
Follow the same steps as the Quick Start:
https://magic-network.github.io/magic-agent/provider/gateway/quick-start/gateway-server-setup.html

Depending on permissions on the Pi, you may need to modify the steps above with sudo.

**Comment by magicpia** [comment]
@DomAmato if you're up for giving this install guide a shot we can finally push the guide to production. LMK!

**Comment by DomAmato** [comment]
I was actually planning on doing it this weekend to try and capture any issues I run into 😄 I'll update it and take some photos while I am at it

**Comment by DomAmato** [comment]
We're working on several user guides for installing Magic Agent on different setups. In the meantime, here are some notes for the Raspberry Pi to get folks started (cc: @drmartens). Let us know if you encounter issues in this thread. We'll iterate through it and publish a document once its stable.

## Using a Raspberry Pi as a Gateway
For this tutorial, we’ve dedicated a Raspberry Pi 3 Model B to serve as a gateway. 

If you already have a Pi setup that is connected to an existing internet connection, simply follow the instructions below to install Magic Agent on the Pi.

If you are starting from scratch and need to setup your Pi follow the “Start from scratch” instructions [forthcoming].


## Raspberry Pi Pre-requisites
- Running Raspbian (Lite is sufficient)
- Connected to the internet

Note: The Pi should be connected to the internet on the same network as you are planning to install Magic and needs to maintain internet connectivity in order to serve as a gateway for Magic Clients to connect through.

## Install Magic Pre-requisites
**Update**
Some packages may fail to resolve if you don't upgrade
```sudo apt update```

**Install git**
```sudo apt install git```

**Install pip**
```sudo apt install python-pip```

**Install Docker**
```curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh```

**Add to user to Docker**
If you read the output of the docker install script it will tell you to add the user to the docker group by running

```sudo usermod -aG docker pi```

**Install Docker Compose**
As of 5/14/2019 installing docker-compose through pip will fail giving the error:
`Error: TypeError: unsupported operand types for -=: 'Retry' and 'int'`

Currently you have to first install an old version
```sudo apt install docker-compose```

and then upgrade to a newer version, but not the newest version, since that also fails to install due to https://github.com/docker/compose/issues/6617
```sudo pip install docker-compose==1.23.2```

**Reboot**
You won't be able to connect to the Docker daemon until you restart

```sudo reboot```

## Install Magic
Follow the same steps as the Quick Start:
https://magic-network.github.io/magic-agent/provider/gateway/quick-start/gateway-server-setup.html

Depending on permissions on the Pi, you may need to modify the steps above with sudo.
